usb: gadget: mass_storage: Fix build error caused by duplecated commit
drivers/usb/gadget/legacy/mass_storage.c:199:14: error: ‘msg_registered’ undeclared (first use in this function)
  set_bit(0, &msg_registered);
              ^

次の同一内容のcommitが重複しているのが原因。

commit 524b109ce770a7f8ed3503b406e40776e51b80db
Author: Li Jun <jun.li@nxp.com>
Date:   Thu Apr 13 00:02:51 2017 +0800
    MLK-14589 usb: gadget: mass_storage: set msg_registered after msg registered

commit 2b5c7b95ea36521e7cb4f93be546a8be5fd9d667
Author: Li Jun <jun.li@nxp.com>
Date:   Fri Apr 14 19:12:07 2017 +0800
    usb: gadget: mass_storage: set msg_registered after msg registered